<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="api.tests.test_ack_views.AckViewTestCase-20250630235745" tests="16" file="api/tests/test_ack_views.py" time="0.187" timestamp="2025-06-30T23:57:46" failures="0" errors="0" skipped="0">
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_add" time="0.039" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="94"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_add_cert_auth" time="0.022" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="215"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_add_exceptions" time="0.008" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="280"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_add_kessel_enabled_full_write" time="0.025" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="111"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_add_kessel_enabled_only_read" time="0.007" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="111"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_add_service_account" time="0.030" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="246"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_delete" time="0.006" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="330"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_delete_cert_auth" time="0.006" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="346"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_delete_errors" time="0.003" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="378"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_delete_service_account" time="0.006" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="362"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_list" time="0.006" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="38"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_list_all" time="0.009" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="72"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_list_other_account" time="0.003" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="62"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_update_justification" time="0.005" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="295"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_update_justification_cert_auth" time="0.006" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="308"/>
	<testcase classname="api.tests.test_ack_views.AckViewTestCase" name="test_ack_update_justification_exceptions" time="0.003" timestamp="2025-06-30T23:57:46" file="advisor/api/tests/test_ack_views.py" line="321"/>
</testsuite>
